import { Language } from './types';

export const translations = {
  [Language.EN]: {
    appName: 'सब्ज़ीMATE',
    loginTitle: 'Welcome to सब्ज़ीMATE',
    loginSubtitle: 'Your daily fresh vegetable partner',
    loginWithPhone: 'Login with Phone',
    loginWithGoogle: 'Login with Google',
    chooseLanguage: 'Choose your language',
    english: 'English',
    hindi: 'हिन्दी',
    continue: 'Continue',
    home: 'Home',
    urgentOrder: 'Urgent Order',
    location: 'Location',
    bills: 'Bills',
    willYouTakeVeg: 'Will you take vegetables today?',
    yes: 'YES',
    no: 'NO',
    todaysVeggies: "Today's Fresh Vegetables",
    searchPlaceholder: 'Search for vegetables...',
    deliveryConfirmation: "Thanks! We will stop at your house today.",
    noDeliveryConfirmation: "Okay! We will not stop at your house today. See you tomorrow!",
    optionalSelection: 'Optional: Select items you might need to help us stock the truck.',
    confirmSelection: 'Confirm Selection',
    urgentOrderTitle: 'Place an Urgent Order',
    urgentOrderDesc: 'Order anytime. Standard delivery charges will apply.',
    placeOrder: 'Place Order',
    locationTitle: 'Live Truck Location',
    locationDesc: 'Our truck is on its way! Track its live location during delivery hours.',
    billsTitle: 'Your Monthly Bills',
    monthlyTotal: 'Monthly Total',
    payNow: 'Pay Now',
    payWithCash: 'Pay with Cash',
    loading: 'Loading...',
    // Onboarding & Profile
    setupProfile: 'Setup Your Profile',
    fullName: 'Full Name',
    phoneNumber: 'Phone Number',
    address: 'Delivery Address',
    useMap: 'Use Map',
    saveAndContinue: 'Save & Continue',
    yourProfile: 'Your Profile',
    edit: 'Edit',
    save: 'Save',
    // Modal
    updateOrder: 'Update Order',
    close: 'Close',
  },
  [Language.HI]: {
    appName: 'सब्ज़ीMATE',
    loginTitle: 'सब्ज़ीMATE में आपका स्वागत है',
    loginSubtitle: 'आपका दैनिक ताजा सब्जी का साथी',
    loginWithPhone: 'फोन से लॉगिन करें',
    loginWithGoogle: 'गूगल से लॉगिन करें',
    chooseLanguage: 'अपनी भाषा चुनें',
    english: 'English',
    hindi: 'हिन्दी',
    continue: 'जारी रखें',
    home: 'होम',
    urgentOrder: 'जरूरी ऑर्डर',
    location: 'लोकेशन',
    bills: 'बिल',
    willYouTakeVeg: 'क्या आप आज सब्जियां लेंगे?',
    yes: 'हाँ',
    no: 'नहीं',
    todaysVeggies: 'आज की ताज़ा सब्ज़ियाँ',
    searchPlaceholder: 'सब्जियां खोजें...',
    deliveryConfirmation: "धन्यवाद! हम आज आपके घर पर रुकेंगे।",
    noDeliveryConfirmation: "ठीक है! हम आज आपके घर पर नहीं रुकेंगे। कल मिलते हैं!",
    optionalSelection: 'वैकल्पिक: उन वस्तुओं का चयन करें जिनकी आपको आवश्यकता हो सकती है ताकि हमें ट्रक स्टॉक करने में मदद मिल सके।',
    confirmSelection: 'चयन की पुष्टि करें',
    urgentOrderTitle: 'एक तत्काल आदेश दें',
    urgentOrderDesc: 'किसी भी समय ऑर्डर करें। मानक वितरण शुल्क लागू होंगे।',
    placeOrder: 'ऑर्डर दें',
    locationTitle: 'लाइव ट्रक लोकेशन',
    locationDesc: 'हमारा ट्रक रास्ते में है! डिलीवरी के घंटों के दौरान इसका लाइव लोकेशन ट्रैक करें।',
    billsTitle: 'आपके मासिक बिल',
    monthlyTotal: 'मासिक कुल',
    payNow: 'अभी भुगतान करें',
    payWithCash: 'नकद में भुगतान करें',
    loading: 'लोड हो रहा है...',
    // Onboarding & Profile
    setupProfile: 'अपनी प्रोफ़ाइल सेटअप करें',
    fullName: 'पूरा नाम',
    phoneNumber: 'फ़ोन नंबर',
    address: 'डिलीवरी का पता',
    useMap: 'नक्शे का प्रयोग करें',
    saveAndContinue: 'सहेजें और जारी रखें',
    yourProfile: 'आपकी प्रोफ़ाइल',
    edit: 'संपादित करें',
    save: 'सहेजें',
    // Modal
    updateOrder: 'ऑर्डर अपडेट करें',
    close: 'बंद करें',
  },
};